name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        # 文字列
        # type: string
        # default: Hello
        # 列挙型
        type: choice
        options:
          - info
          - warn
          - error
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
